"""Capture formal-lab-contracts/v2 replay bundles produced by the phase-2 code (run once, at 0ae4571).

These are the phase-3 compatibility baseline for v2 data (G1): later code must keep reading them — the turn-based
two-dispatcher run with task plans and planner checkpoints, the order-service run with reconciled operations and
probes (a persistent session environment), and the warehouse run (second semantic profile, namespaced payload).
They are committed and never regenerated by later revisions.

    scripts/in-vm.sh 'uv run --frozen python tests/compat/capture_phase2.py'   # only meaningful at 0ae4571
"""

from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path

from formal_lab_contracts import CONTRACT_VERSION
from formal_lab_runtime import default_registry, make_manifest, run_local
from formal_lab_runtime.bundles import bundle_from_local

OUT = Path(__file__).parent / "fixtures" / "phase2"


def capture(name: str, result, package, summary: dict) -> None:
    (OUT / f"{name}.replay.zip").write_bytes(bundle_from_local(result, package, provenance={"captured_by": __file__}))
    summary[name] = {"status": result.status.value, "reason": getattr(result, "reason", None),
                     "events": len(result.events), "operations": len(getattr(result, "operations", []) or []),
                     "participants": [p.actor_id for p in result.manifest.participants],
                     "metrics": {m.metric_id: m.value for m in result.metrics}}


def main() -> None:
    assert CONTRACT_VERSION == "formal-lab-contracts/v2", "run at a phase-2 revision"
    OUT.mkdir(parents=True, exist_ok=True)
    reg = default_registry()
    summary: dict = {}

    from formal_lab_example_scheduling.scenarios import model_package, two_dispatchers

    pkg = model_package()
    sc = two_dispatchers(pkg, seed=1, strategies=("task-rule", "task-symbolic"), timing="ROUND_START")
    m = make_manifest(run_id="run_phase2_two_dispatchers", project_id="prj_phase2", scenario=sc, package=pkg,
                      registry=reg, seed=1, config={"initial_check_horizon": 0})
    capture("two-dispatchers", run_local(m, pkg, reg), pkg, summary)

    from formal_lab_example_warehouse.scenarios import package as wh_package
    from formal_lab_example_warehouse.scenarios import receiver_and_picker

    wpkg = wh_package()
    m = make_manifest(run_id="run_phase2_warehouse", project_id="prj_phase2", scenario=receiver_and_picker(wpkg, seed=1),
                      package=wpkg, registry=reg, seed=1, config={"initial_check_horizon": 0})
    capture("warehouse", run_local(m, wpkg, reg), wpkg, summary)

    from formal_lab_example_orders.lifecycle import ServiceManager
    from formal_lab_example_orders.model import model_package as orders_package
    from formal_lab_example_orders.scenarios import run as orders_run

    with tempfile.TemporaryDirectory() as tmp:
        mgr = ServiceManager(Path(tmp), project="capture-phase2").start()
        try:
            mgr.ready()
            res = orders_run("delayed", backend="service", seed=1, endpoint=mgr.endpoint, tenant="phase2",
                             run_id="run_phase2_orders_delayed", registry=reg)
            capture("orders-delayed", res, orders_package(), summary)
        finally:
            mgr.close()

    digest = json.loads((Path(__file__).parents[2] / "contracts" / "v2" / "DIGEST.json").read_text())["digest"]
    rev = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()
    (OUT / "CAPTURE.json").write_text(json.dumps(
        {"contract_version": CONTRACT_VERSION, "contract_digest": digest, "source_revision": rev, "runs": summary,
         "note": "phase-2 v2 compatibility baseline; do not regenerate"}, indent=2, ensure_ascii=False) + "\n")
    print(json.dumps(summary, indent=1, ensure_ascii=False))


if __name__ == "__main__":
    main()
