"""Capture formal-lab-contracts/v1 objects produced by the phase-1 code (run once, at commit 46400ad).

These files are the compatibility baseline of phase 2 (P2-003 / P2-014 / P2-110): later code must keep reading
them — v1 JSON through the v1→v2 adapters, the replay bundle through the v1 bundle reader. They are committed and
never regenerated by later revisions (the phase-1 code that wrote them no longer exists at HEAD).

    uv run python tests/compat/capture_phase1.py     # only meaningful at the phase-1 revision
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

from formal_lab_contracts import CONTRACT_VERSION
from formal_lab_contracts.bundle import ReplayBundle, write_bundle
from formal_lab_example_scheduling.scenarios import STRATEGIES, model_package, scenario
from formal_lab_runtime import default_registry, make_manifest
from formal_lab_runtime.local_runner import run_local

OUT = Path(__file__).parent / "fixtures" / "phase1"


def dump(name: str, obj) -> None:
    (OUT / name).write_text(json.dumps(obj, indent=2, sort_keys=True, ensure_ascii=False) + "\n")


def main() -> None:
    assert CONTRACT_VERSION == "formal-lab-contracts/v1", "run at the phase-1 revision"
    OUT.mkdir(parents=True, exist_ok=True)
    reg = default_registry()
    pkg = model_package()
    dump("ModelPackage.json", pkg.model_dump(mode="json"))
    runs = {}
    for key, strategy in (("normal", "rule"), ("state-delay", "z3")):
        sc = scenario(key, pkg, seed=1, strategy=STRATEGIES[strategy])
        dump(f"ScenarioManifest.{key}.json", sc.model_dump(mode="json"))
        m = make_manifest(run_id=f"run_phase1_{key.replace('-', '_')}", project_id="prj_phase1", scenario=sc,
                          package=pkg, registry=reg, seed=1)
        res = run_local(m, pkg, reg)
        runs[key] = {"status": res.status.value, "reason": res.reason, "events": len(res.events),
                     "metrics": {x.metric_id: x.value for x in res.metrics}}
        bundle = ReplayBundle(manifest=res.manifest, events=res.events, package=pkg, metrics=res.metrics)
        (OUT / f"{key}.replay.zip").write_bytes(write_bundle(bundle, provenance={"captured_by": __file__}))
        if key == "normal":
            dump("RunManifest.json", res.manifest.model_dump(mode="json"))
            dump("TraceEvents.sample.json", [e.model_dump(mode="json") for e in res.events[:12]])
            checks = [e.payload["result"] for e in res.events if str(e.event_type) == "CHECK_COMPLETED"][:3]
            dump("BoundedCheckResult.samples.json", checks)
            dump("MetricResults.json", [x.model_dump(mode="json") for x in res.metrics])
    dump("PluginDescriptors.json", [e.descriptor.model_dump(mode="json") for e in reg.entries()])
    rev = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip()
    dump("CAPTURE.json", {"contract_version": CONTRACT_VERSION, "source_revision": rev, "runs": runs,
                          "note": "phase-1 compatibility baseline; do not regenerate"})
    print(json.dumps(runs, indent=1))


if __name__ == "__main__":
    main()
