"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 22:56:11.285620
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_catalog',
    sa.Column('plugin_id', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('interface', sa.String(length=40), nullable=False),
    sa.Column('descriptor', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('descriptor_digest', sa.String(length=64), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('plugin_id', 'version')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrices_project_id'), 'matrices', ['project_id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('package_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'package_id')
    )
    op.create_index(op.f('ix_models_project_id'), 'models', ['project_id'], unique=False)
    op.create_table('strategy_configs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plugin_id', sa.String(length=200), nullable=False),
    sa.Column('plugin_version', sa.String(length=40), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_configs_project_id'), 'strategy_configs', ['project_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('semantic_profile', sa.String(length=80), nullable=False),
    sa.Column('package', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parent_version', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'version')
    )
    op.create_index(op.f('ix_model_versions_digest'), 'model_versions', ['digest'], unique=False)
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.create_table('checks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('model_version_id', sa.String(length=40), nullable=False),
    sa.Column('query', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verdict', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checks_model_version_id'), 'checks', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_checks_project_id'), 'checks', ['project_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('model_version_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('copied_from', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_model_version_id'), 'scenarios', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_scenarios_project_id'), 'scenarios', ['project_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('scenario_id', sa.String(length=40), nullable=True),
    sa.Column('strategy_config_id', sa.String(length=40), nullable=True),
    sa.Column('matrix_id', sa.String(length=40), nullable=True),
    sa.Column('source_run_id', sa.String(length=40), nullable=True),
    sa.Column('client_request_id', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('workflow_id', sa.String(length=80), nullable=True),
    sa.Column('event_seq', sa.BigInteger(), nullable=False),
    sa.Column('last_step', sa.Integer(), nullable=False),
    sa.Column('usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('paused_seconds', sa.Float(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('final_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('imported', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matrix_id'], ['matrices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_config_id'], ['strategy_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'client_request_id')
    )
    op.create_index(op.f('ix_runs_matrix_id'), 'runs', ['matrix_id'], unique=False)
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_scenario_id'), 'runs', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_runs_source_run_id'), 'runs', ['source_run_id'], unique=False)
    op.create_index(op.f('ix_runs_status'), 'runs', ['status'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('ref', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'digest', 'kind')
    )
    op.create_index(op.f('ix_artifacts_digest'), 'artifacts', ['digest'], unique=False)
    op.create_index(op.f('ix_artifacts_run_id'), 'artifacts', ['run_id'], unique=False)
    op.create_table('env_snapshots',
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('state_revision', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('artifact', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'step')
    )
    op.create_table('metrics',
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('metric_id', sa.String(length=80), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'metric_id')
    )
    op.create_table('operations',
    sa.Column('operation_id', sa.String(length=120), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('operation_id')
    )
    op.create_index(op.f('ix_operations_run_id'), 'operations', ['run_id'], unique=False)
    op.create_table('run_events',
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('logical_step', sa.Integer(), nullable=True),
    sa.Column('wall_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.String(length=80), nullable=True),
    sa.Column('causal_parents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('payload_schema', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'seq'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('run_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_run_events_event_type'), 'run_events', ['event_type'], unique=False)
    op.create_index('ix_run_events_run_step', 'run_events', ['run_id', 'logical_step'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_events_run_step', table_name='run_events')
    op.drop_index(op.f('ix_run_events_event_type'), table_name='run_events')
    op.drop_table('run_events')
    op.drop_index(op.f('ix_operations_run_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_table('metrics')
    op.drop_table('env_snapshots')
    op.drop_index(op.f('ix_artifacts_run_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_digest'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_runs_status'), table_name='runs')
    op.drop_index(op.f('ix_runs_source_run_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_scenario_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_matrix_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_scenarios_project_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_model_version_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_checks_project_id'), table_name='checks')
    op.drop_index(op.f('ix_checks_model_version_id'), table_name='checks')
    op.drop_table('checks')
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_digest'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_strategy_configs_project_id'), table_name='strategy_configs')
    op.drop_table('strategy_configs')
    op.drop_index(op.f('ix_models_project_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_matrices_project_id'), table_name='matrices')
    op.drop_table('matrices')
    op.drop_table('projects')
    op.drop_table('plugin_catalog')
    # ### end Alembic commands ###
