"""Resource-allocation game: the typed model payload of the PRISM-games extension (P2-X01).

A finite, turn-based, fully observed stochastic game. Each round:

1. the **dispatcher** assigns some of the unfinished jobs to distinct machines (at least one job);
2. the **environment** slows one machine (adversarial disturbance; with `adversary=False` it has a single "calm"
   choice and the game is an MDP for the dispatcher);
3. the machines **work**: a job on machine m finishes with probability `success(m)`, multiplied by `slowdown` on the
   slowed machine, independently per job. The round counter moves on.

The game ends when every job is finished (goal) or after `rounds` rounds. Randomness is only in step 3 and is given
by explicit probabilities; both players see the whole state. This module turns the payload into PRISM-games input
(`to_prism`) and solves it independently of PRISM (`solve`, `evaluate`) so a PRISM result can be checked in-model.
"""

from __future__ import annotations

import itertools
import re
from dataclasses import dataclass
from functools import cache

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

NAMESPACE = "org.formal-lab.prism-games"
GAME_SCHEMA = f"{NAMESPACE}/allocation-game@1"
PROFILE = "prism_smg_turn_based_v1"
ASSUMPTIONS = [
    "finite state space: jobs ≤ 3, machines ≤ 3, rounds ≤ 8",
    "turn-based: in every state exactly one player chooses (dispatcher, then environment, then the stochastic work step)",
    "fully observed: both players see finished jobs, the round and the current assignment",
    "stochastic transitions only in the work step, with the explicit per-machine success probabilities",
    "the environment is adversarial for robust queries (<<dispatcher>>) and cooperative for <<dispatcher,environment>>",
]
_ID = re.compile(r"^[a-z][a-z0-9]{0,15}$")


class Machine(BaseModel):
    model_config = ConfigDict(extra="forbid")
    id: str
    success: float = Field(gt=0, le=1, description="probability that a job on this machine finishes in one round")

    @field_validator("id")
    @classmethod
    def _ident(cls, v: str) -> str:
        if not _ID.match(v):
            raise ValueError("machine ids are lower-case letters/digits, starting with a letter (≤ 16)")
        return v


class AllocationGame(BaseModel):
    model_config = ConfigDict(extra="forbid")
    game_id: str = Field(min_length=1, max_length=80)
    jobs: list[str] = Field(min_length=1, max_length=3)
    machines: list[Machine] = Field(min_length=1, max_length=3)
    rounds: int = Field(ge=1, le=8)
    slowdown: float = Field(ge=0, le=1, description="success multiplier on the machine the environment slows")
    adversary: bool = True
    description: str | None = None

    @field_validator("jobs")
    @classmethod
    def _jobs(cls, v: list[str]) -> list[str]:
        if any(not _ID.match(j) for j in v) or len(set(v)) != len(v):
            raise ValueError("job ids must be distinct lower-case identifiers")
        return v

    @model_validator(mode="after")
    def _distinct(self) -> AllocationGame:
        if len({m.id for m in self.machines}) != len(self.machines):
            raise ValueError("machine ids must be distinct")
        return self

    # ------------------------------------------------------------------ structure shared by PRISM and the solver
    def assignments(self) -> list[tuple[tuple[str, int], ...]]:
        """Every dispatcher choice: a non-empty partial injective map job → machine index (1-based)."""
        out = []
        idx = range(1, len(self.machines) + 1)
        for k in range(1, len(self.jobs) + 1):
            for js in itertools.combinations(self.jobs, k):
                for ms in itertools.permutations(idx, k):
                    out.append(tuple(zip(js, ms, strict=True)))
        return out

    def action_name(self, assignment: tuple[tuple[str, int], ...]) -> str:
        return "asg_" + "_".join(f"{j}_{self.machines[m - 1].id}" for j, m in assignment)

    def slow_actions(self) -> list[tuple[str, int]]:
        if not self.adversary:
            return [("calm", 0)]
        return [(f"slow_{m.id}", i) for i, m in enumerate(self.machines, start=1)]

    def finish_probability(self, machine: int, slowed: int) -> float:
        p = self.machines[machine - 1].success
        return p * (self.slowdown if slowed == machine else 1.0)


def to_prism(game: AllocationGame) -> str:
    """PRISM-games model (smg) of the game; variable order t, r, d_<job>…, x_<job>…, sl."""
    m = len(game.machines)
    lines = [f"// {game.game_id}: generated by formal_lab_solver_prism.game.to_prism from {GAME_SCHEMA}",
             "// dispatcher assigns jobs, environment slows a machine, machines work (stochastic)", "smg", "",
             f"const int K = {game.rounds};", f"const double s = {game.slowdown!r};"]
    lines += [f"const double p_{mc.id} = {mc.success!r};" for mc in game.machines]
    dispatcher = [f"[{game.action_name(a)}]" for a in game.assignments()]
    environment = [f"[{name}]" for name, _ in game.slow_actions()] + ["[work]"]
    lines += ["", f"player dispatcher {', '.join(dispatcher)} endplayer",
              f"player environment {', '.join(environment)} endplayer", ""]
    for j in game.jobs:  # finish probability of job j this round, from its machine and the slowed machine
        expr = "0"
        for i in range(m, 0, -1):
            expr = f"(x_{j}={i} ? p_{game.machines[i - 1].id} : {expr})"
        lines.append(f"formula q_{j} = {expr} * (sl>0 & sl=x_{j} ? s : 1);")
    lines += ["", "module plant", "  t : [0..2] init 0;  // 0 dispatcher, 1 environment, 2 work",
              "  r : [0..K] init 0;"]
    lines += [f"  d_{j} : bool init false;" for j in game.jobs]
    lines += [f"  x_{j} : [0..{m}] init 0;" for j in game.jobs]
    lines += [f"  sl : [0..{m}] init 0;", ""]
    for a in game.assignments():
        assigned = dict(a)
        guard = " & ".join(["t=0", "r<K", *[f"!d_{j}" for j in assigned]])
        upd = " & ".join([*(f"(x_{j}'={assigned.get(j, 0)})" for j in game.jobs), "(t'=1)"])
        lines.append(f"  [{game.action_name(a)}] {guard} -> {upd};")
    for name, i in game.slow_actions():
        lines.append(f"  [{name}] t=1 -> (sl'={i}) & (t'=2);")
    reset = " & ".join([*(f"(x_{j}'=0)" for j in game.jobs), "(sl'=0)", "(t'=0)", "(r'=r+1)"])
    branches = []
    for outcome in itertools.product([True, False], repeat=len(game.jobs)):
        prob = "*".join(f"q_{j}" if ok else f"(1-q_{j})" for j, ok in zip(game.jobs, outcome, strict=True))
        done = [f"(d_{j}'=d_{j}|x_{j}>0)" for j, ok in zip(game.jobs, outcome, strict=True) if ok]
        branches.append(f"{prob} : {' & '.join([*done, reset])}")
    lines.append("  [work] t=2 -> " + "\n              + ".join(branches) + ";")
    lines += ["endmodule", "", f"label \"done\" = {' & '.join(f'd_{j}' for j in game.jobs)};", ""]
    return "\n".join(lines)


ROBUST = '<<dispatcher>> Pmax=? [ F "done" ]'
COOPERATIVE = '<<dispatcher,environment>> Pmax=? [ F "done" ]'


# ============================================================================ independent solver (no PRISM)
@dataclass(frozen=True)
class Solution:
    value: float
    policy: dict[tuple[int, frozenset[str]], str]  # (round, finished jobs) → dispatcher action at the value
    states: int  # reachable states of the full (t, r, d, x, sl) graph — must equal PRISM's count


def _outcomes(game: AllocationGame, assignment: tuple[tuple[str, int], ...], slowed: int):
    qs = [(j, game.finish_probability(m, slowed)) for j, m in assignment]
    for bits in itertools.product([True, False], repeat=len(qs)):
        p = 1.0
        for (_, q), ok in zip(qs, bits, strict=True):
            p *= q if ok else 1 - q
        if p > 0:
            yield p, frozenset(j for (j, _), ok in zip(qs, bits, strict=True) if ok)


def solve(game: AllocationGame, *, cooperative: bool = False) -> Solution:
    """Backward induction over rounds (the graph is acyclic: every round increments r)."""
    everything = frozenset(game.jobs)
    choose_env = max if cooperative else min

    @cache
    def value(r: int, done: frozenset[str]) -> tuple[float, str | None]:
        if done == everything:
            return 1.0, None
        if r == game.rounds:
            return 0.0, None
        best, best_a = -1.0, None
        for a in game.assignments():
            if any(j in done for j, _ in a):
                continue
            v = choose_env(sum(p * value(r + 1, done | fin)[0] for p, fin in _outcomes(game, a, sl))
                           for _, sl in game.slow_actions())
            if v > best + 1e-15:
                best, best_a = v, game.action_name(a)
        return best, best_a

    v0 = value(0, frozenset())[0]
    policy = {}
    for r in range(game.rounds):
        for k in range(len(game.jobs)):
            for done in itertools.combinations(game.jobs, k):
                _, a = value(r, frozenset(done))
                if a:
                    policy[(r, frozenset(done))] = a
    return Solution(value=v0, policy=policy, states=_count_states(game))


def evaluate(game: AllocationGame, strategy: dict[tuple[int, frozenset[str]], str]) -> float:
    """Probability that the dispatcher strategy finishes every job against the worst-case environment."""
    everything = frozenset(game.jobs)
    by_name = {game.action_name(a): a for a in game.assignments()}

    @cache
    def value(r: int, done: frozenset[str]) -> float:
        if done == everything:
            return 1.0
        if r == game.rounds:
            return 0.0
        a = by_name[strategy[(r, done)]]
        return min(sum(p * value(r + 1, done | fin) for p, fin in _outcomes(game, a, sl))
                   for _, sl in game.slow_actions())

    return value(0, frozenset())


def _count_states(game: AllocationGame) -> int:
    """Reachable states of the PRISM encoding: (t, r, finished, assignment, slowed)."""
    everything = frozenset(game.jobs)
    start = (0, 0, frozenset(), (), 0)
    seen, stack = {start}, [start]
    while stack:
        t, r, done, asg, sl = stack.pop()
        nxt = []
        if t == 0 and r < game.rounds and done != everything:
            nxt = [(1, r, done, a, 0) for a in game.assignments() if not any(j in done for j, _ in a)]
        elif t == 1:
            nxt = [(2, r, done, asg, s) for _, s in game.slow_actions()]
        elif t == 2:
            nxt = [(0, r + 1, done | fin, (), 0) for _, fin in _outcomes(game, asg, sl)]
        for n in nxt:
            if n not in seen:
                seen.add(n)
                stack.append(n)
    return len(seen)


EXAMPLE = AllocationGame(
    game_id="two-jobs-two-machines",
    description="two jobs, a reliable and a less reliable machine, an adversary that halves one machine's rate "
                "each round, three rounds",
    jobs=["a", "b"], machines=[Machine(id="m1", success=0.9), Machine(id="m2", success=0.6)],
    rounds=3, slowdown=0.5)
