{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "fal.fullname" . }}-migrate-{{ .Release.Revision }}
  labels: {{- include "fal.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    spec:
      restartPolicy: Never
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: {{ include "fal.image" (dict "root" . "component" "api") }}
          command: ["fal-migrate", "upgrade"]
          env:
            {{- include "fal.env" . | nindent 12 }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
{{- end }}
