// Generate TypeScript types from the canonical JSON Schema bundle (single source: Pydantic models).
import { compile } from "json-schema-to-typescript";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../..");
// Types describe what the platform emits (serialization view); ajv tests validate against bundle.schema.json.
const bundle = JSON.parse(await readFile(path.join(root, "contracts/v1/bundle.serialization.schema.json"), "utf8"));
const digest = JSON.parse(await readFile(path.join(root, "contracts/v1/DIGEST.json"), "utf8"));
const objects = JSON.parse(await readFile(path.join(root, "contracts/v1/objects.json"), "utf8"));

const types = await compile(bundle, "FormalLabContractsV1", {
  bannerComment: "/* eslint-disable */\n// GENERATED from contracts/v1/bundle.serialization.schema.json by scripts/generate.mjs — do not edit.",
  additionalProperties: false,
  unreachableDefinitions: true,
  strictIndexSignatures: true,
  format: true,
  style: { singleQuote: false, printWidth: 110 },
});
await writeFile(path.join(here, "../src/generated.ts"), types);

const meta = `// GENERATED by scripts/generate.mjs — do not edit.
export const CONTRACT_VERSION = ${JSON.stringify(digest.contract_version)} as const;
export const CONTRACT_DIGEST = ${JSON.stringify(digest.digest)} as const;
export const FROZEN_OBJECTS = ${JSON.stringify(objects.frozen_objects)} as const;
export const ERROR_CODES = ${JSON.stringify(objects.error_codes)} as const;
export const QUERY_KINDS = ${JSON.stringify(objects.query_kinds)} as const;
export const SEARCH_VERDICTS = ${JSON.stringify(objects.search_verdicts)} as const;
export const PRECONDITION_VERDICTS = ${JSON.stringify(objects.precondition_verdicts)} as const;
export const RUN_STATUSES = ${JSON.stringify(objects.run_statuses)} as const;
export const EVENT_TYPES = ${JSON.stringify(objects.event_types)} as const;
`;
await writeFile(path.join(here, "../src/meta.ts"), meta);
console.log(`generated TypeScript for ${digest.contract_version} (${digest.digest.slice(0, 12)})`);
