// Generate TypeScript types from the canonical JSON Schema bundles (single source: Pydantic models).
//   src/generated.ts     formal-lab-contracts/v2 (what the platform emits now)
//   src/generated.v1.ts  formal-lab-contracts/v1 (frozen; for reading phase-1 data), exported as namespace V1
import { compile } from "json-schema-to-typescript";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../../..");
const readJson = async (p) => JSON.parse(await readFile(path.join(root, p), "utf8"));
const options = (version) => ({
  bannerComment: `/* eslint-disable */\n// GENERATED from contracts/${version}/bundle.serialization.schema.json by scripts/generate.mjs — do not edit.`,
  additionalProperties: false,
  unreachableDefinitions: true,
  strictIndexSignatures: true,
  format: true,
  style: { singleQuote: false, printWidth: 110 },
});

// Types describe what the platform emits (serialization view); ajv tests validate against bundle.schema.json.
for (const [version, file, title] of [["v2", "generated.ts", "FormalLabContractsV2"],
                                      ["v1", "generated.v1.ts", "FormalLabContractsV1"]]) {
  const bundle = await readJson(`contracts/${version}/bundle.serialization.schema.json`);
  await writeFile(path.join(here, "../src", file), await compile(bundle, title, options(version)));
}

const digest = await readJson("contracts/v2/DIGEST.json");
const digestV1 = await readJson("contracts/v1/DIGEST.json");
const objects = await readJson("contracts/v2/objects.json");
const meta = `// GENERATED by scripts/generate.mjs — do not edit.
export const CONTRACT_VERSION = ${JSON.stringify(digest.contract_version)} as const;
export const CONTRACT_DIGEST = ${JSON.stringify(digest.digest)} as const;
export const CONTRACT_VERSION_V1 = ${JSON.stringify(digestV1.contract_version)} as const;
export const CONTRACT_DIGEST_V1 = ${JSON.stringify(digestV1.digest)} as const;
export const FROZEN_OBJECTS = ${JSON.stringify(objects.frozen_objects)} as const;
export const V2_OBJECTS = ${JSON.stringify(objects.v2_objects)} as const;
export const ERROR_CODES = ${JSON.stringify(objects.error_codes)} as const;
export const PLUGIN_INTERFACES = ${JSON.stringify(objects.plugin_interfaces)} as const;
export const QUERY_KINDS = ${JSON.stringify(objects.query_kinds)} as const;
export const SEARCH_VERDICTS = ${JSON.stringify(objects.search_verdicts)} as const;
export const PRECONDITION_VERDICTS = ${JSON.stringify(objects.precondition_verdicts)} as const;
export const OPTIMIZATION_STATUSES = ${JSON.stringify(objects.optimization_statuses)} as const;
export const ROBUSTNESS_VERDICTS = ${JSON.stringify(objects.robustness_verdicts)} as const;
export const RUN_STATUSES = ${JSON.stringify(objects.run_statuses)} as const;
export const TERMINATION_REASONS = ${JSON.stringify(objects.termination_reasons)} as const;
export const EVENT_TYPES = ${JSON.stringify(objects.event_types)} as const;
export const EXECUTION_STAGES = ${JSON.stringify(objects.execution_stages)} as const;
export const OPERATION_STATES = ${JSON.stringify(objects.operation_states)} as const;
export const PROVENANCE = ${JSON.stringify(objects.provenance)} as const;
`;
await writeFile(path.join(here, "../src/meta.ts"), meta);
console.log(`generated TypeScript for ${digest.contract_version} (${digest.digest.slice(0, 12)}) and v1 (${digestV1.digest.slice(0, 12)})`);
