"""CAGE 4 platform scenarios (phase 4B, B2): five platform-controlled blue agents, one joint batch per world step.

Scenario variants are fixed here, before any policy was tuned:
  * `dev`     — red FiniteStateRedAgent (the official Scenario4 red);
  * `holdout` — red DiscoveryFSRed (an official variant), never used to adjust a blue policy.
Topology is generated by CybORG from the seed, so a different seed is a different network of the same scenario —
changing seeds alone is not a claim about other topologies or scenarios.
"""

from __future__ import annotations

from typing import Any

from formal_lab_contracts import ModelPackage, ScenarioManifest

ENV = {"plugin_id": "formal-lab.env.cage4", "version": "1.0.0"}
DRIVER = {"plugin_id": "formal-lab.driver.cage4", "version": "1.0.0"}
POLICIES = {"sleep": "formal-lab.cage4.blue-sleep", "monitor": "formal-lab.cage4.blue-monitor",
            "react": "formal-lab.cage4.blue-react"}
VARIANTS = {"dev": "FiniteStateRedAgent", "holdout": "DiscoveryFSRed"}
BLUE = [f"blue_agent_{i}" for i in range(5)]


def scenario(pkg: ModelPackage, *, policy: str = "react", variant: str = "dev", steps: int = 30, seed: int = 0,
             world_log: str | None = None, extra_env: dict[str, Any] | None = None) -> ScenarioManifest:
    env: dict[str, Any] = {"steps": steps, "red": VARIANTS[variant], "blue_native": "SleepAgent",
                           **(extra_env or {})}
    if world_log:
        env["world_log"] = world_log
    strategy = {"plugin": {"plugin_id": POLICIES[policy], "version": "1.0.0"}, "config": {}}
    return ScenarioManifest(
        scenario_id=f"cage4-{variant}-{policy}", name=f"CAGE 4 · {variant} · 蓝方 {policy}", model=pkg.ref(),
        description=f"CybORG 4.0 Scenario4, red {VARIANTS[variant]} (native), green EnterpriseGreenAgent (native "
                    f"normal business), five blue agents controlled by the platform ({policy}); {steps} world steps",
        environment={"plugin": ENV, "config": env}, driver=DRIVER,
        participants=[{"actor_id": a, "role": "defender", "strategy": strategy} for a in BLUE],
        objectives=[{"property_id": "episode_complete", "description": "the native episode ran to its end"}],
        budget={"max_steps": steps * len(BLUE) + 10, "max_wall_seconds": 3600, "max_model_calls": 0},
        seed=seed, turns={"mode": "JOINT_BATCH", "observation_timing": "ROUND_START"},
        termination={"joint_goal": "episode_complete", "on_no_action": "SKIP_ACTOR"})
