#!/usr/bin/env python3
"""Write web/src/tokens.css from design/tokens.json (the single source of the visual system, phase 3A G5).

    python3 scripts/design_tokens.py           # regenerate
    python3 scripts/design_tokens.py --check   # fail if tokens.css is out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "design" / "tokens.json"
TARGET = ROOT / "web" / "src" / "tokens.css"


def load() -> dict:
    return json.loads(SOURCE.read_text())


def scheme(t: dict, mode: str) -> list[str]:
    out = [f"  --color-{k}: {v};" for k, v in t["color"][mode].items()]
    out += [f"  --p{i + 1}: {v};" for i, v in enumerate(t["participant"][mode])]
    out += [f"  --ev-{k}: {v[mode]};" for k, v in t["evidence"].items() if isinstance(v, dict)]
    out += [f"  --shadow-{k}: {v};" for k, v in t["shadow"][mode].items()]
    return out


def css(t: dict) -> str:
    common = [f"  --font-{k}: {v};" for k, v in t["font"].items()]
    for k, (size, line) in t["text"].items():
        common += [f"  --text-{k}: {size}px;", f"  --leading-{k}: {line}px;"]
    common += [f"  --weight-{k}: {v};" for k, v in t["weight"].items()]
    common += [f"  --space-{k}: {v}px;" for k, v in t["space"].items()]
    common += [f"  --radius-{k}: {v}px;" for k, v in t["radius"].items()]
    common += [f"  --dur-{k}: {v}ms;" for k, v in t["motion"]["duration"].items()]
    common += [f"  --ease-{k}: {v};" for k, v in t["motion"]["easing"].items()]
    common += [f"  --layout-{k}: {v}px;" for k, v in t["layout"].items() if not k.startswith("breakpoint")]
    lines = [
        "/* GENERATED by scripts/design_tokens.py from design/tokens.json — do not edit by hand. */",
        f"/* {t['name']} v{t['version']} */",
        ":root {", *common, *scheme(t, "light"), "  color-scheme: light;", "}",
        "@media (prefers-color-scheme: dark) {", "  :root:not([data-theme=\"light\"]) {",
        *("  " + x for x in scheme(t, "dark")), "    color-scheme: dark;", "  }", "}",
        ":root[data-theme=\"dark\"] {", *scheme(t, "dark"), "  color-scheme: dark;", "}",
        "@media (prefers-reduced-motion: reduce) {",
        "  :root { " + " ".join(f"--dur-{k}: 0ms;" for k in t["motion"]["duration"]) + " }",
        "}", "",
    ]
    return "\n".join(lines)


def main() -> int:
    text = css(load())
    if "--check" in sys.argv:
        if not TARGET.exists() or TARGET.read_text() != text:
            print(f"{TARGET.relative_to(ROOT)} is out of date: run python3 scripts/design_tokens.py")
            return 1
        print("tokens.css up to date")
        return 0
    TARGET.write_text(text)
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
