#!/usr/bin/env python3
"""Order service vs pure-data model: comparison report and environment declarations (P2-064 … P2-067).

Starts a supervised order service (lifecycle manager, loopback), then for every case runs the rule strategy on both
backends with the same seed and compares them step by step (candidate preconditions, outcomes, every state field,
evidence). Adds two deliberate contrasts: the nominal pure model against the service with a slow station (the
effect differences are located by step, operation and field) and two handlers committing on stale observations
(the service's conditional update vs the pure model's revision check). Also records what each environment declares:
capabilities, recovery modes, deployment profiles, and the probe metrics with their window semantics.

Writes docs/execution/evidence/phase2/orders/comparison.{json,md}.

    scripts/in-vm.sh 'uv run --frozen python scripts/orders_report.py'
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

from formal_lab_example_orders.compare import compare_runs, markdown
from formal_lab_example_orders.env import DESCRIPTOR as SERVICE_ENV
from formal_lab_example_orders.instance import CASES
from formal_lab_example_orders.lifecycle import ServiceManager
from formal_lab_example_orders.plugins import PROBE_METRICS
from formal_lab_example_orders.scenarios import run
from formal_lab_runtime import default_registry

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs/execution/evidence/phase2/orders"
SEED = 2


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    reg = default_registry()
    pure_env = reg.latest("formal-lab.env.ir-world").descriptor
    report: dict = {"seed": SEED, "strategy": "rule", "cases": {}, "contrasts": {}}
    md = ["# Order service vs pure-data model (P2-066)", "",
          f"Rule strategy, seed {SEED}; generated by `scripts/orders_report.py`. Each comparison aligns the two runs "
          "step by step and compares candidate preconditions, outcomes, every state field after the step, and "
          "evidence; a difference names the step, both operation ids and the field.", ""]
    with tempfile.TemporaryDirectory() as tmp, ServiceManager(Path(tmp), project="report", supervise=True) as mgr:
        mgr.ready()
        for case in CASES:
            pure = run(case, backend="pure", seed=SEED, registry=reg, run_id=f"run_rep_{case}_pure")
            svc = run(case, backend="service", seed=SEED, endpoint=mgr.endpoint, tenant=f"rep-{case}", registry=reg,
                      run_id=f"run_rep_{case}_svc")
            cmp = compare_runs(pure, svc)
            ops: dict[str, int] = {}
            for o in svc.operations:
                ops[o.state.value] = ops.get(o.state.value, 0) + 1
            cmp["service_operations"] = ops
            report["cases"][case] = cmp
            md.append(markdown(f"{case} — {CASES[case]['label']}: service operations {ops}", cmp))
        nominal = run("normal", backend="pure", seed=SEED, registry=reg, run_id="run_rep_nominal")
        slow = run("deviation", backend="service", seed=SEED, endpoint=mgr.endpoint, tenant="rep-slow", registry=reg,
                   run_id="run_rep_slow")
        report["contrasts"]["nominal-model-vs-slow-service"] = compare_runs(nominal, slow)
        md.append(markdown("contrast: nominal pure model vs service with slow station p2",
                           report["contrasts"]["nominal-model-vs-slow-service"], limit=25))
        kw = {"two_actors": True, "timing": "ROUND_START", "conflict_policy": "REJECT_STALE", "registry": reg}
        p2 = run("normal", backend="pure", seed=SEED, run_id="run_rep_stale_pure", **kw)
        s2 = run("normal", backend="service", seed=SEED, endpoint=mgr.endpoint, tenant="rep-stale",
                 run_id="run_rep_stale_svc", **kw)
        conflicts = {name: [{"step": e.logical_step, "operation": e.payload["outcome"]["operation_id"],
                             "reason": e.payload["outcome"]["result"].get("reason"),
                             "changed_paths": e.payload["outcome"]["conflict"]["changed_paths"]}
                            for e in r.events if str(e.event_type) == "ACTION_OUTCOME"
                            and e.payload["outcome"].get("conflict")] for name, r in (("pure", p2), ("service", s2))}
        report["contrasts"]["stale-observations"] = {"comparison": compare_runs(p2, s2), "conflicts": conflicts}
        md.append(markdown("contrast: two handlers, round-start observations, REJECT_STALE",
                           report["contrasts"]["stale-observations"]["comparison"], limit=25))
        md += ["First stale commits refused — pure (revision check on the IR read set) vs service (conditional "
               "update on row revisions):", "", "| backend | step | operation | reason | changed locations |",
               "|---|---|---|---|---|"]
        for name, rows in conflicts.items():
            for c in rows[:4]:
                md.append(f"| {name} | {c['step']} | `{c['operation']}` | {c['reason']} | "
                          f"{', '.join(c['changed_paths'][:6])} |")
        md.append("")
    decl = {}
    for d in (pure_env, SERVICE_ENV):
        caps = {c.id: c.params for c in d.capabilities}
        decl[d.plugin_id] = {"capabilities": sorted(caps),
                             "recovery_modes": ["RESEED", "SNAPSHOT"] if "env.pure_replayable" in caps else
                             caps.get("env.persistent_session", {}).get("recovery_modes", []),
                             "deployment_profiles": caps.get("env.persistent_session", {}).get("deployment_profiles",
                                                                                            {"all": "in-process"})}
    report["environments"] = decl
    report["probe_metrics"] = [d.model_dump(mode="json", include={"metric_id", "unit", "description"})
                               for d in PROBE_METRICS]
    md += ["## Environment declarations (P2-050 / P2-067)", "", "| environment | recovery modes | capabilities |",
           "|---|---|---|"]
    md += [f"| `{k}` | {', '.join(v['recovery_modes'])} | {', '.join(v['capabilities'])} |" for k, v in decl.items()]
    md += ["", "## Probe metrics (P2-064)", "", "| metric | unit | meaning / window |", "|---|---|---|"]
    md += [f"| {d.metric_id} | {d.unit} | {d.description} |" for d in PROBE_METRICS]
    (OUT / "comparison.json").write_text(json.dumps(report, indent=2, ensure_ascii=False, default=str) + "\n")
    (OUT / "comparison.md").write_text("\n".join(md) + "\n")
    same = all(not c["differences"] for c in report["cases"].values())
    located = all(d["pure_operation"] and d["service_operation"]
                  for d in report["contrasts"]["nominal-model-vs-slow-service"]["differences"])
    print(json.dumps({c: len(v["differences"]) for c, v in report["cases"].items()}),
          len(report["contrasts"]["nominal-model-vs-slow-service"]["differences"]), same, located)
    return 0 if same and located else 1


if __name__ == "__main__":
    sys.exit(main())
