#!/usr/bin/env python3
"""Strategy behaviour on the state-delay scenario (P2-047).

Runs every scheduling strategy that needs no network on `state-delay` for several seeds, twice: with the phase-1
ending (goal / budget only) and with a no-progress stop (v2 termination, `no_progress_limit`). For each run it records
how it ended (status, termination reason, the engine's stop text), how much it achieved (orders completed, delay
cost, makespan) and how it got there (steps, rejected actions, the longest run of turns without a state change,
observation requests served / declined as repeats, plan versions).

Writes docs/execution/evidence/phase2/state-delay/report.json and report.md. Deterministic: rerunning it gives the
same numbers (the Z3 planner uses a fresh context per query, D-017).

    scripts/in-vm.sh 'uv run --frozen python scripts/state_delay_report.py'
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from formal_lab_example_scheduling.__main__ import EVALUATORS
from formal_lab_example_scheduling.scenarios import STRATEGIES, model_package, scenario
from formal_lab_runtime import default_registry, make_manifest, run_local

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / os.environ.get("FAL_EVIDENCE_DIR", "docs/execution/evidence/phase2") / "state-delay"
STRATEGY_NAMES = ["rule", "z3", "llm-stub", "task-rule", "task-symbolic", "task-model-stub"]
SEEDS = [1, 2, 3, 4, 5]
NO_PROGRESS_LIMIT = 20  # above the longest stall of any strategy that still reaches the goal (rule: 18)
METRICS = ["orders_completed", "delay_cost", "makespan"]


def longest_stall(events) -> int:
    best = cur = 0
    for e in events:
        if str(e.event_type) != "ACTION_OUTCOME":
            continue
        o = e.payload["outcome"]
        changed = (o.get("revision_after") or o.get("revision_before")) != o.get("revision_before")
        cur = 0 if changed else cur + 1
        best = max(best, cur)
    return best


def one(pkg, reg, name: str, seed: int, limit: int | None) -> dict:
    sc = scenario("state-delay", pkg, seed=seed, strategy=STRATEGIES[name], no_progress_limit=limit)
    run_id = f"run_sd_{name.replace('-', '_')}_{seed}_{limit or 0}"
    manifest = make_manifest(run_id=run_id, project_id="report", scenario=sc, package=pkg, registry=reg, seed=seed,
                             evaluators=EVALUATORS)
    r = run_local(manifest, pkg, reg)
    ev = r.events
    kinds = [str(e.event_type) for e in ev]
    requests = [e for e in ev if str(e.event_type) == "OBSERVATION_REQUESTED"]
    outcomes = [e.payload["outcome"] for e in ev if str(e.event_type) == "ACTION_OUTCOME"]
    metric = {m: (r.metric(m).value if r.metric(m) is not None else None) for m in METRICS}
    return {
        "strategy": name, "seed": seed, "no_progress_limit": limit,
        "status": r.status.value, "termination_reason": r.termination_reason.value if r.termination_reason else None,
        "stop_text": r.reason, "steps": r.usage.steps,
        "applied": sum(1 for o in outcomes if o["status"] == "APPLIED"),
        "rejected": sum(1 for o in outcomes if o["status"] == "REJECTED"),
        "longest_stall": longest_stall(ev),
        "observation_requests_served": sum(1 for e in requests if e.payload.get("served", True)),
        "observation_requests_declined": sum(1 for e in requests if e.payload.get("served") is False),
        "plan_versions": kinds.count("PLAN_UPDATED"),
        "model_calls": r.usage.model_calls,
        **metric,
    }


def summarise(rows: list[dict]) -> list[dict]:
    out = []
    for limit in (None, NO_PROGRESS_LIMIT):
        for name in STRATEGY_NAMES:
            mine = [r for r in rows if r["strategy"] == name and r["no_progress_limit"] == limit]
            ok = [r for r in mine if r["status"] == "SUCCEEDED"]
            mean = lambda k, rs: round(sum(r[k] for r in rs) / len(rs), 2) if rs else None  # noqa: E731
            out.append({
                "strategy": name, "no_progress_limit": limit, "runs": len(mine), "succeeded": len(ok),
                "endings": sorted({f"{r['status']}/{r['termination_reason']}" for r in mine}),
                "mean_steps": mean("steps", mine), "mean_rejected": mean("rejected", mine),
                "max_stall": max(r["longest_stall"] for r in mine),
                "mean_obs_requests": mean("observation_requests_served", mine),
                "declined_repeats": sum(r["observation_requests_declined"] for r in mine),
                "mean_delay_cost_succeeded": mean("delay_cost", ok),
                "mean_makespan_succeeded": mean("makespan", ok),
            })
    return out


def markdown(summary: list[dict], rows: list[dict]) -> str:
    lines = [
        "# state-delay: strategy behaviour (P2-047)",
        "",
        "Generated by `scripts/state_delay_report.py` (deterministic; seeds "
        f"{SEEDS}). `state-delay` observes machine occupancy and operation phases with a delay, so a belief can "
        "show a machine free that is busy (or an operation idle that the dispatcher itself just started).",
        "",
        "## Summary",
        "",
        "| strategy | no-progress stop | succeeded | endings | mean steps | mean rejected | longest stall | "
        "obs. requests (mean) | declined repeats | delay cost (ok runs) | makespan (ok runs) |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for s in summary:
        lines.append(
            f"| {s['strategy']} | {s['no_progress_limit'] or '—'} | {s['succeeded']}/{s['runs']} | "
            f"{', '.join(s['endings'])} | {s['mean_steps']} | {s['mean_rejected']} | {s['max_stall']} | "
            f"{s['mean_obs_requests']} | {s['declined_repeats']} | {s['mean_delay_cost_succeeded']} | "
            f"{s['mean_makespan_succeeded']} |")
    lines += [
        "",
        "## What differs and why",
        "",
        "- **rule** (phase-1 heuristic) treats UNKNOWN candidates as worth trying: roughly half of its turns are "
        "rejected assignments to machines the delayed belief shows free, with stalls of up to 18 turns; one seed runs "
        "the step budget out.",
        "- **z3** re-plans from the belief after every rejection (a new plan version each time): it never stalls "
        "more than two turns, but still spends a third of its turns on rejections.",
        "- **llm-stub** (labelled stand-in for the model planner) keeps choosing the first UNKNOWN assignment and "
        "stalls for the rest of the run: without a no-progress stop it burns the whole step budget "
        f"(BUDGET_EXHAUSTED); with `no_progress_limit={NO_PROGRESS_LIMIT}` it ends as FAILED/NO_PROGRESS after "
        f"{NO_PROGRESS_LIMIT} turns without a state change, the stop text naming the stall — a result with a reason "
        "instead of a burnt budget. The limit is chosen above the longest stall of a strategy that still succeeds.",
        "- **task-*** (task plans from the rule / Z3 / model generator) keep a working state: the freshest value "
        "per location plus the predicted effects of their own applied actions, and dispatch only what is applicable "
        "on it. They neither dispatch an operation twice nor retry a machine they know is busy: no rejected action, "
        "no stall, the goal in about the steps of the undelayed scenario and the lowest delay cost.",
        "- A repeated observation request for the same locations with an unchanged world revision is declined and "
        "recorded (`OBSERVATION_REQUESTED` with `served: false`); the strategy then decides without it.",
        "- A no-candidate turn ends the run with NO_APPLICABLE_ACTION (phase-1 behaviour, unchanged).",
        "",
        "## Runs",
        "",
        "| strategy | seed | stop | status | reason | steps | rejected | stall | obs. served / declined | plans | "
        "orders | delay cost |",
        "|---|---|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['strategy']} | {r['seed']} | {r['no_progress_limit'] or '—'} | {r['status']} | "
            f"{r['termination_reason']} | {r['steps']} | {r['rejected']} | {r['longest_stall']} | "
            f"{r['observation_requests_served']} / {r['observation_requests_declined']} | {r['plan_versions']} | "
            f"{r['orders_completed']} | {r['delay_cost']} |")
    return "\n".join(line.replace("| None ", "| — ") for line in lines) + "\n"


def main() -> int:
    reg = default_registry()
    pkg = model_package()
    rows = [one(pkg, reg, name, seed, limit) for limit in (None, NO_PROGRESS_LIMIT) for name in STRATEGY_NAMES
            for seed in SEEDS]
    summary = summarise(rows)
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "report.json").write_text(json.dumps({"scenario": "state-delay", "seeds": SEEDS,
                                                 "no_progress_limit": NO_PROGRESS_LIMIT, "summary": summary,
                                                 "runs": rows}, indent=2, ensure_ascii=False) + "\n")
    (OUT / "report.md").write_text(markdown(summary, rows))
    for s in summary:
        print(json.dumps(s, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
